### ISSUE TITLE
[Main] recommendation slider 수정

### ISSUE THREAD

**Issue by soryeongk** [colfume/colfume-frontend#22]
## 💡 이슈 제목

[Main] recommendation slider 수정

## ✨ 이슈 설명

- [x] recomm 화살표 위치
- [x] recomm 사진 간 구분 선 넣기
- [x] 슬라이더 아래 dots style 변경
- [x] 메인뷰 전체 마진값 조정

## 🎯 이슈 생성 후 확인 내용
- [x] 이슈 제목 확인 
- [x] Assignees 설정 
- [x] Labels 설정 
- [x] Projects 설정

**Comment by mnxmnz** [comment]
최고예요
