### ISSUE TITLE
[Main] feat: footer 구현

### ISSUE THREAD

**Issue by yezgoget** [colfume/colfume-frontend#24]
## 💡 이슈 제목
footer 구현

## ✨ 이슈 설명
![image](https://user-images.githubusercontent.com/55784772/124446836-bfb70e80-ddbb-11eb-980c-588e826ab17d.png)

https://www.figma.com/file/Zjmg2zHGhAREtbJgim9ME7/Colfume_plan-dev-design?node-id=514%3A651

## 🎯 이슈 생성 후 확인 내용
- [x] 이슈 제목 확인 
- [x] Assignees 설정 
- [x] Labels 설정 
- [x] Projects 설정

**Comment by mnxmnz** [comment]
멋져요

**Comment by yezgoget** [comment]
https://www.figma.com/file/Zjmg2zHGhAREtbJgim9ME7/Colfume_plan-dev-design?node-id=514%3A651
