### ISSUE TITLE
[Test/Questions] feat: 컴포넌트 생성하고 퍼블리싱 작업

### ISSUE THREAD

**Issue by mnxmnz** [colfume/colfume-frontend#29]
## 💡 이슈 제목
[Test/Questions] feat: 컴포넌트 생성하고 퍼블리싱 작업

## ✨ 이슈 설명
- [ ] result 와 분리하기 위해 questions 폴더 생성
- [ ] 퍼블리싱 작업
- [ ] result 페이지와 공통으로 사용되는 컴포넌트를 활용하기 위해 공용 컴포넌트 생성

## 🎯 이슈 생성 후 확인 내용
- [x] 이슈 제목 확인 
- [x] Assignees 설정 
- [x] Labels 설정 
- [x] Projects 설정

**Comment by yezgoget** [comment]
사랑해 눈민지

**Comment by mnxmnz** [comment]
> 사랑해 눈민지

내가 더 ❤❤❤
